version: "3"

networks:
  custom:
services:
  etcd0:
    image: quay.io/coreos/etcd
    container_name: etcd0
    networks:
      - custom
    ports:
      - 2379:2379
    volumes:
      - ./etcd0:/etcd_data
    command:
        - etcd
        - -name
        - etcd0
        - --data-dir
        - /etcd_data
        - -advertise-client-urls
        - http://etcd0:2379
        - -listen-client-urls
        - http://0.0.0.0:2379
        - -initial-advertise-peer-urls
        - http://etcd0:2380
        - -listen-peer-urls
        - http://0.0.0.0:2380
        - -initial-cluster
        - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380
  etcd1:
    image: quay.io/coreos/etcd
    container_name: etcd1
    networks:
      - custom
    ports:
      - 2379
    volumes:
      - ./etcd1:/etcd_data
    command:
      - etcd
      - -name
      - etcd1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd1:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd1:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380
