version: "3"

networks:
  etcd_custom:
    external: true
services:
  kube-node0:
    build: .
    image: kube-node
    container_name: kube-node0
    dns:
      - 8.8.8.8
    networks:
      - etcd_custom
    privileged: true
    environment:
      - ETCD_ENDPOINTS=http://etcd0:2379/
      - ETCD_PREFIX=/k8s/
      - NODE_NAME=kube-node0
      - NODE_LABELS=group=k8s-demo
    external_links:
      - etcd0
      - etcd1
      - cube-master
  kube-node1:
    image: kube-node
    container_name: kube-node1
    depends_on:
      - kube-node0
    dns:
      - 8.8.8.8
    networks:
      - etcd_custom
    privileged: true
    environment:
      - ETCD_ENDPOINTS=http://etcd0:2379/
      - ETCD_PREFIX=/k8s/
      - NODE_NAME=kube-node1
      - NODE_LABELS=group=k8s-demo
    external_links:
      - etcd0
      - etcd1
      - kube-master
