apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80